config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'admin/index'

  root 'home#index'

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :select_layout

  def select_layout
    controller_name == 'home' ? 'public' : 'admin'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.haml
.row
  .col-lg-3.col-xs-6
    / small box
    .small-box.bg-aqua
      .inner
        %h3 150
        %p New Orders
      .icon
        %i.ion.ion-bag
      %a.small-box-footer{:href => "#"}
        More info
        %i.fa.fa-arrow-circle-right
  / ./col
  .col-lg-3.col-xs-6
    / small box
    .small-box.bg-green
      .inner
        %h3
          53
          %sup{:style => "font-size: 20px"} %
        %p Bounce Rate
      .icon
        %i.ion.ion-stats-bars
      %a.small-box-footer{:href => "#"}
        More info
        %i.fa.fa-arrow-circle-right
  / ./col
  .col-lg-3.col-xs-6
    / small box
    .small-box.bg-yellow
      .inner
        %h3 44
        %p User Registrations
      .icon
        %i.ion.ion-person-add
      %a.small-box-footer{:href => "#"}
        More info
        %i.fa.fa-arrow-circle-right
  / ./col
  .col-lg-3.col-xs-6
    / small box
    .small-box.bg-red
      .inner
        %h3 65
        %p Unique Visitors
      .icon
        %i.ion.ion-pie-graph
      %a.small-box-footer{:href => "#"}
        More info
        %i.fa.fa-arrow-circle-right
  / ./col
/ /.row
/ Main row
.row
  / Left col
  %section.col-lg-7.connectedSortable
    / Custom tabs (Charts with tabs)
    .nav-tabs-custom
      / Tabs within a box
      %ul.nav.nav-tabs.pull-right
        %li.active
          %a{"data-toggle" => "tab", :href => "#revenue-chart"} Area
        %li
          %a{"data-toggle" => "tab", :href => "#sales-chart"} Donut
        %li.pull-left.header
          %i.fa.fa-inbox
          Sales
      .tab-content.no-padding
        / Morris chart - Sales
        #revenue-chart.chart.tab-pane.active{:style => "position: relative; height: 300px;"}
        #sales-chart.chart.tab-pane{:style => "position: relative; height: 300px;"}
    / /.nav-tabs-custom
    / Chat box
    .box.box-success
      .box-header
        %i.fa.fa-comments-o
        %h3.box-title Chat
        .box-tools.pull-right{"data-toggle" => "tooltip", :title => "Status"}
          .btn-group{"data-toggle" => "btn-toggle"}
            %button.btn.btn-default.btn-sm.active{:type => "button"}
              %i.fa.fa-square.text-green
            %button.btn.btn-default.btn-sm{:type => "button"}
              %i.fa.fa-square.text-red
      #chat-box.box-body.chat
        / chat item
        .item
          = image_tag 'admin_lte/user4-128x128.jpg', class: 'online'
          %p.message
            %a.name{:href => "#"}
              %small.text-muted.pull-right
                %i.fa.fa-clock-o
                2:15
              Mike Doe
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
          .attachment
            %h4 Attachments:
            %p.filename
              Theme-thumbnail-image.jpg
            .pull-right
              %button.btn.btn-primary.btn-sm.btn-flat Open
        / /.attachment
        / /.item
        / chat item
        .item
          = image_tag 'admin_lte/user3-128x128.jpg', class: 'offline'
          %p.message
            %a.name{:href => "#"}
              %small.text-muted.pull-right
                %i.fa.fa-clock-o
                5:15
              Alexander Pierce
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
        / /.item
        / chat item
        .item
          = image_tag 'admin_lte/user2-160x160.jpg', class: 'offline'
          %p.message
            %a.name{:href => "#"}
              %small.text-muted.pull-right
                %i.fa.fa-clock-o
                5:30
              Susan Doe
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
      / /.item
      / /.chat
      .box-footer
        .input-group
          %input.form-control{:placeholder => "Type message..."}/
          .input-group-btn
            %button.btn.btn-success
              %i.fa.fa-plus
    / /.box (chat box)
    / TO DO List
    .box.box-primary
      .box-header
        %i.ion.ion-clipboard
        %h3.box-title To Do List
        .box-tools.pull-right
          %ul.pagination.pagination-sm.inline
            %li
              %a{:href => "#"} &laquo;
            %li
              %a{:href => "#"} 1
            %li
              %a{:href => "#"} 2
            %li
              %a{:href => "#"} 3
            %li
              %a{:href => "#"} &raquo;
      / /.box-header
      .box-body
        %ul.todo-list
          %li
            / drag handle
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            / checkbox
            %input{:name => "", :type => "checkbox", :value => ""}/
            / todo text
            %span.text Design a nice theme
            / Emphasis label
            %small.label.label-danger
              %i.fa.fa-clock-o
              2 mins
            / General tools such as edit or delete
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
          %li
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            %input{:name => "", :type => "checkbox", :value => ""}/
            %span.text Make the theme responsive
            %small.label.label-info
              %i.fa.fa-clock-o
              4 hours
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
          %li
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            %input{:name => "", :type => "checkbox", :value => ""}/
            %span.text Let theme shine like a star
            %small.label.label-warning
              %i.fa.fa-clock-o
              1 day
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
          %li
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            %input{:name => "", :type => "checkbox", :value => ""}/
            %span.text Let theme shine like a star
            %small.label.label-success
              %i.fa.fa-clock-o
              3 days
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
          %li
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            %input{:name => "", :type => "checkbox", :value => ""}/
            %span.text Check your messages and notifications
            %small.label.label-primary
              %i.fa.fa-clock-o
              1 week
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
          %li
            %span.handle
              %i.fa.fa-ellipsis-v
              %i.fa.fa-ellipsis-v
            %input{:name => "", :type => "checkbox", :value => ""}/
            %span.text Let theme shine like a star
            %small.label.label-default
              %i.fa.fa-clock-o
              1 month
            .tools
              %i.fa.fa-edit
              %i.fa.fa-trash-o
      / /.box-body
      .box-footer.clearfix.no-border
        %button.btn.btn-default.pull-right
          %i.fa.fa-plus
          Add item
    / /.box
    / quick email widget
    .box.box-info
      .box-header
        %i.fa.fa-envelope
        %h3.box-title Quick Email
        / tools box
        .pull-right.box-tools
          %button.btn.btn-info.btn-sm{"data-toggle" => "tooltip", "data-widget" => "remove", :title => "Remove"}
            %i.fa.fa-times
      / /. tools
      .box-body
        %form{:action => "#", :method => "post"}
          .form-group
            %input.form-control{:name => "emailto", :placeholder => "Email to:", :type => "email"}/
          .form-group
            %input.form-control{:name => "subject", :placeholder => "Subject", :type => "text"}/
          %div
            %textarea.textarea{:placeholder => "Message", :style => "width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"}
      .box-footer.clearfix
        %button#sendEmail.pull-right.btn.btn-default
          Send
          %i.fa.fa-arrow-circle-right
  / /.Left col
  / right col (We are only adding the ID to make the widgets sortable)
  %section.col-lg-5.connectedSortable
    / Map box
    .box.box-solid.bg-light-blue-gradient
      .box-header
        / tools box
        .pull-right.box-tools
          %button.btn.btn-primary.btn-sm.daterange.pull-right{"data-toggle" => "tooltip", :title => "Date range"}
            %i.fa.fa-calendar
          %button.btn.btn-primary.btn-sm.pull-right{"data-toggle" => "tooltip", "data-widget" => "collapse", :style => "margin-right: 5px;", :title => "Collapse"}
            %i.fa.fa-minus
        / /. tools
        %i.fa.fa-map-marker
        %h3.box-title
          Visitors
      .box-body
        #world-map{:style => "height: 250px; width: 100%;"}
      / /.box-body
      .box-footer.no-border
        .row
          .col-xs-4.text-center{:style => "border-right: 1px solid #f4f4f4"}
            #sparkline-1
            .knob-label Visitors
          / ./col
          .col-xs-4.text-center{:style => "border-right: 1px solid #f4f4f4"}
            #sparkline-2
            .knob-label Online
          / ./col
          .col-xs-4.text-center
            #sparkline-3
            .knob-label Exists
    / ./col
    / /.row
    / /.box
    / solid sales graph
    .box.box-solid.bg-teal-gradient
      .box-header
        %i.fa.fa-th
        %h3.box-title Sales Graph
        .box-tools.pull-right
          %button.btn.bg-teal.btn-sm{"data-widget" => "collapse"}
            %i.fa.fa-minus
          %button.btn.bg-teal.btn-sm{"data-widget" => "remove"}
            %i.fa.fa-times
      .box-body.border-radius-none
        #line-chart.chart{:style => "height: 250px;"}
      / /.box-body
      .box-footer.no-border
        .row
          .col-xs-4.text-center{:style => "border-right: 1px solid #f4f4f4"}
            %input.knob{"data-fgColor" => "#39CCCC", "data-height" => "60", "data-readonly" => "true", "data-width" => "60", :type => "text", :value => "20"}/
            .knob-label Mail-Orders
          / ./col
          .col-xs-4.text-center{:style => "border-right: 1px solid #f4f4f4"}
            %input.knob{"data-fgColor" => "#39CCCC", "data-height" => "60", "data-readonly" => "true", "data-width" => "60", :type => "text", :value => "50"}/
            .knob-label Online
          / ./col
          .col-xs-4.text-center
            %input.knob{"data-fgColor" => "#39CCCC", "data-height" => "60", "data-readonly" => "true", "data-width" => "60", :type => "text", :value => "30"}/
            .knob-label In-Store
    / ./col
    / /.row
    / /.box-footer
    / /.box
    / Calendar
    .box.box-solid.bg-green-gradient
      .box-header
        %i.fa.fa-calendar
        %h3.box-title Calendar
        / tools box
        .pull-right.box-tools
          / button with a dropdown
          .btn-group
            %button.btn.btn-success.btn-sm.dropdown-toggle{"data-toggle" => "dropdown"}
              %i.fa.fa-bars
            %ul.dropdown-menu.pull-right{:role => "menu"}
              %li
                %a{:href => "#"} Add new event
              %li
                %a{:href => "#"} Clear events
              %li.divider
              %li
                %a{:href => "#"} View calendar
          %button.btn.btn-success.btn-sm{"data-widget" => "collapse"}
            %i.fa.fa-minus
          %button.btn.btn-success.btn-sm{"data-widget" => "remove"}
            %i.fa.fa-times
      / /. tools
      / /.box-header
      .box-body.no-padding
        / The calendar
        #calendar{:style => "width: 100%"}
      / /.box-body
      .box-footer.text-black
        .row
          .col-sm-6
            / Progress bars
            .clearfix
              %span.pull-left Task #1
              %small.pull-right 90%
            .progress.xs
              .progress-bar.progress-bar-green{:style => "width: 90%;"}
            .clearfix
              %span.pull-left Task #2
              %small.pull-right 70%
            .progress.xs
              .progress-bar.progress-bar-green{:style => "width: 70%;"}
          / /.col
          .col-sm-6
            .clearfix
              %span.pull-left Task #3
              %small.pull-right 60%
            .progress.xs
              .progress-bar.progress-bar-green{:style => "width: 60%;"}
            .clearfix
              %span.pull-left Task #4
              %small.pull-right 40%
            .progress.xs
              .progress-bar.progress-bar-green{:style => "width: 40%;"}

app/views/home/index.html.haml
.login-box
  .login-logo
    %a{:href => "../../index2.html"}
      %b> Admin
      LTE
  / /.login-logo
  .login-box-body
    %p.login-box-msg Sign in to start your session
    %form{:action => "../../index2.html", :method => "post"}
      .form-group.has-feedback
        %input.form-control{:placeholder => "Email", :type => "email"}/
        %span.glyphicon.glyphicon-envelope.form-control-feedback
      .form-group.has-feedback
        %input.form-control{:placeholder => "Password", :type => "password"}/
        %span.glyphicon.glyphicon-lock.form-control-feedback
      .row
        .col-xs-8
          .checkbox.icheck
            %label
              %input{:type => "checkbox"}
                Remember Me
        / /.col
        .col-xs-4
          = link_to 'Sign In', admin_index_path, class: 'btn btn-primary btn-block btn-flat'
          -#%button.btn.btn-primary.btn-block.btn-flat{:type => "submit"} Sign In
    %a{:href => "#"} I forgot my password
    %br
      %a.text-center{:href => "register.html"} Register a new membership

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title AdminLTE
    -#Include style per-controller - vendor plugins
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    -#Main css styles
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    -#Main javascript files
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body.skin-blue.sidebar-mini
    .wrapper
      = render partial: 'layouts/admin/header'
      = render partial: 'layouts/admin/sidebar'
      / Content Wrapper. Contains page content
      .content-wrapper
        = render 'layouts/admin/content_header'
        %section.content
          = yield
      = render partial: 'layouts/public/footer'

    -#Include javascript per-controller - vendor plugins
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")

    -#Include javascript per-view
    = yield :javascript

app/views/layouts/admin/_content_header.html.haml
%section.content-header
  %h1
    Dashboard
    %small Control panel
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Dashboard

app/views/layouts/admin/_header.html.haml
%header.main-header
  / Logo
  %a.logo{:href => "index2.html"}
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      %b> A
      LT
    / logo for regular state and mobile devices
    %span.logo-lg
      %b> Admin
      LTE
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / Messages: style can be found in dropdown.less
        %li.dropdown.messages-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-envelope-o
            %span.label.label-success 4
          %ul.dropdown-menu
            %li.header You have 4 messages
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  / start message
                  %a{:href => "#"}
                    .pull-left
                      = image_tag 'admin_lte/user2-160x160.jpg', class: 'img-circle'
                    %h4
                      Support Team
                      %small
                        %i.fa.fa-clock-o
                        5 mins
                    %p Why not buy a new awesome theme?
                / end message
                %li
                  %a{:href => "#"}
                    .pull-left
                      = image_tag 'admin_lte/user3-128x128.jpg', class: 'img-circle'
                    %h4
                      AdminLTE Design Team
                      %small
                        %i.fa.fa-clock-o
                        2 hours
                    %p Why not buy a new awesome theme?
                %li
                  %a{:href => "#"}
                    .pull-left
                      = image_tag 'admin_lte/user4-128x128.jpg', class: 'img-circle'
                    %h4
                      Developers
                      %small
                        %i.fa.fa-clock-o
                        Today
                    %p Why not buy a new awesome theme?
                %li
                  %a{:href => "#"}
                    .pull-left
                      = image_tag 'admin_lte/user3-128x128.jpg', class: 'img-circle'
                    %h4
                      Sales Department
                      %small
                        %i.fa.fa-clock-o
                        Yesterday
                    %p Why not buy a new awesome theme?
                %li
                  %a{:href => "#"}
                    .pull-left
                      = image_tag 'admin_lte/user4-128x128.jpg', class: 'img-circle'
                    %h4
                      Reviewers
                      %small
                        %i.fa.fa-clock-o
                        2 days
                    %p Why not buy a new awesome theme?
            %li.footer
              %a{:href => "#"} See All Messages
        / Notifications: style can be found in dropdown.less
        %li.dropdown.notifications-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-bell-o
            %span.label.label-warning 10
          %ul.dropdown-menu
            %li.header You have 10 notifications
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  %a{:href => "#"}
                    %i.fa.fa-users.text-aqua
                    5 new members joined today
                %li
                  %a{:href => "#"}
                    %i.fa.fa-warning.text-yellow
                    Very long description here that may not fit into the page and may cause design problems
                %li
                  %a{:href => "#"}
                    %i.fa.fa-users.text-red
                    5 new members joined
                %li
                  %a{:href => "#"}
                    %i.fa.fa-shopping-cart.text-green
                    25 sales made
                %li
                  %a{:href => "#"}
                    %i.fa.fa-user.text-red
                    You changed your username
            %li.footer
              %a{:href => "#"} View all
        / Tasks: style can be found in dropdown.less
        %li.dropdown.tasks-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-flag-o
            %span.label.label-danger 9
          %ul.dropdown-menu
            %li.header You have 9 tasks
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  / Task item
                  %a{:href => "#"}
                    %h3
                      Design some buttons
                      %small.pull-right 20%
                    .progress.xs
                      .progress-bar.progress-bar-aqua{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                        %span.sr-only 20% Complete
                / end task item
                %li
                  / Task item
                  %a{:href => "#"}
                    %h3
                      Create a nice theme
                      %small.pull-right 40%
                    .progress.xs
                      .progress-bar.progress-bar-green{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 40%"}
                        %span.sr-only 40% Complete
                / end task item
                %li
                  / Task item
                  %a{:href => "#"}
                    %h3
                      Some task I need to do
                      %small.pull-right 60%
                    .progress.xs
                      .progress-bar.progress-bar-red{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 60%"}
                        %span.sr-only 60% Complete
                / end task item
                %li
                  / Task item
                  %a{:href => "#"}
                    %h3
                      Make beautiful transitions
                      %small.pull-right 80%
                    .progress.xs
                      .progress-bar.progress-bar-yellow{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 80%"}
                        %span.sr-only 80% Complete
            / end task item
            %li.footer
              %a{:href => "#"} View all tasks
        / User Account: style can be found in dropdown.less
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = image_tag 'admin_lte/user2-160x160.jpg', class: 'user-image'
            %span.hidden-xs Alexander Pierce
          %ul.dropdown-menu
            / User image
            %li.user-header
              = image_tag 'admin_lte/user2-160x160.jpg', class: 'img-circle'
              %p
                Alexander Pierce - Web Developer
                %small Member since Nov. 2012
            / Menu Body
            %li.user-body
              .col-xs-4.text-center
                %a{:href => "#"} Followers
              .col-xs-4.text-center
                %a{:href => "#"} Sales
              .col-xs-4.text-center
                %a{:href => "#"} Friends
            / Menu Footer
            %li.user-footer
              .pull-left
                %a.btn.btn-default.btn-flat{:href => "#"} Profile
              .pull-right
                %a.btn.btn-default.btn-flat{:href => "#"} Sign out
        / Control Sidebar Toggle Button
        -#%li
        -#  %a{"data-toggle" => "control-sidebar", :href => "#"}
        -#    %i.fa.fa-gears

app/views/layouts/public.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title AdminLTE
    -#Include style per-controller - vendor plugins
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    -#Main css styles
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    -#Main javascript files
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body.login-page
    = yield

    -#Include javascript per-controller - vendor plugins
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")

    -#Include javascript per-view
    = yield :javascript